language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"

# install dependencies
install:
    - pip install -r requirements.txt
    - pip install pytest pytest-cov --upgrade
    - pip install python-coveralls
    - pip install coverage --upgrade
    - pip install xlrd

# run tests
script:
    - python setup.py install
    - cd pelicun
    - cd tests
    - pytest --cov-config .coveragerc --cov=pelicun

# check for coverage
after_success:
    - coveralls